#表格转作业设置
use_header: False # excel是否存在表头
color_list: ["绿", "蓝"] # 颜色对应列表，例如 ["绿", "蓝"]，表示敌方1号位对应表格绿色，敌方2号位(右滑)对应表格蓝色
round_post_delay: 2000 # 回合识别延迟

level_type: "白鹄" # 关卡类型：主线，白鹄，洞窟，活动有分级，其他
cave_type: "左" # 洞窟类型：左，右
level_recognition_name: "其他" # 活动有分级/其他-关卡序号/名
difficulty: "" # 活动有分级-难度

json_name: "actions" # 输出的作业名

#表格识别设置
excel_name: "actions" # 如果使用图片转excel，生成的excel文件名
use_team_img: True # 图片中是否使用队伍图片

#通用设置
use_color: True # 是否需要识别图片中的颜色[黑、灰、白、红、橙、黄、绿、青、蓝、紫等]
