#基础功能设置

#auto_fight_gen
#1.输入输出设置
use_header: False # 输入中excel是否存在表头,可选["True","False"]。False表示第一行就是第一回合，True表示第二行是第一回合
json_name: "actions" # 输出的作业名
#2.关卡选择设置
level_type: "其他" # 关卡类型，可选["主线","白鹄","洞窟","活动有分级","其他"]
cave_type: "左" # 洞窟类型,可选["左","右"],只有level_type是洞窟时才需要设置
level_recognition_name: "其他" #活动关卡名，只有level_type是活动有分级时才需要设置
difficulty: "" # 活动关卡难度，只有level_type是活动有分级时才需要设置
round_post_delay: 2000 # 回合识别延迟

#img2xls
api_key: "xxx" # API Key
model: "glm-4v-flash" # 使用的模型名称，可选["glm-4v-flash","glm-4v-plus-0111"],其中只有glm-4v-flash免费
excel_name: "actions" # 输出的表格名
img_url: "xxx"

#进阶功能设置
#1.颜色功能设置，用颜色表示打几号位
use_color: False # 是否需要用这个功能,可选["True","False"](img2xls会识别图片中每个格的颜色，将颜色+文本内容一起保存为表格；auto_fight_gen会自动根据配置的颜色进行左右侧目标选择)[黑、灰、白、红、橙、黄、绿、蓝、紫]
color_list: ["白", "蓝"] # 颜色对应列表，例如 ["绿", "蓝"]，表示敌方1号位对应表格绿色，敌方2号位(右滑)对应表格蓝色
color_type: "fill" # excel中如何表示颜色,可选["fill","text"]："text"表示用文字（如“红”、“橙”、“黄”）来表示颜色，"fill"表示直接填充对应的背景颜色
